#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/reduce
#
# IDENTIFICATION
#    src/backend/reduce/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/reduce
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = adb_reduce.o wait_event.o
include $(top_srcdir)/src/backend/common.mk
