#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for rewrite
#
# IDENTIFICATION
#    src/adbmgrd/rewrite/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/rewrite
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	rewriteDefine.o \
	rewriteHandler.o \
	rewriteManip.o \
	rewriteRemove.o \
	rewriteSearchCycle.o \
	rewriteSupport.o \
	rowsecurity.o

include $(top_srcdir)/src/adbmgrd/common.mk
