#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for adbmgrd/utils/activity
#
# IDENTIFICATION
#    src/adbmgrd/utils/activity/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/activity
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	backend_progress.o \
	backend_status.o \
	wait_event.o

include $(top_srcdir)/src/adbmgrd/common.mk
