#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lib (miscellaneous stuff)
#
# IDENTIFICATION
#    src/adbmgrd/lib/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/lib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = binaryheap.o bipartite_match.o hyperloglog.o ilist.o pairingheap.o \
       rbtree.o stringinfo.o

include $(top_srcdir)/src/adbmgrd/common.mk
