#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/hash
#
# IDENTIFICATION
#    src/adbmgrd/access/hash/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/hash
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hash.o hashfunc.o hashinsert.o hashovfl.o hashpage.o hashsearch.o \
       hashsort.o hashutil.o hashvalidate.o hash_xlog.o

include $(top_srcdir)/src/adbmgrd/common.mk
