#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for tcop
#
# IDENTIFICATION
#    src/adbmgrd/tcop/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/tcop
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	cmdtag.o \
	dest.o \
	fastpath.o \
	postgres.o \
	pquery.o \
	utility.o \
	utility_mgr.o

include $(top_srcdir)/src/adbmgrd/common.mk
