#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for main
#
# IDENTIFICATION
#    src/agtm/main/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/main
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = main.o

include $(top_srcdir)/src/agtm/common.mk
