#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/tablesample
#
# IDENTIFICATION
#    src/adbmgrd/access/tablesample/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/tablesample
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = bernoulli.o system.o tablesample.o

include $(top_srcdir)/src/adbmgrd/common.mk
