#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/sync
#
# IDENTIFICATION
#    src/adbmgrd/storage/sync/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/storage/sync
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = sync.o

include $(top_srcdir)/src/adbmgrd/common.mk
