#
# Makefile for the access methods module
#
# src/adbmgrd/access/Makefile
#

subdir = src/adbmgrd/access
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = brin common gin gist hash heap index nbtree rmgrdesc spgist \
			  table tablesample transam

include $(top_srcdir)/src/adbmgrd/common.mk
