#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/mb
#
# IDENTIFICATION
#    src/adbmgrd/utils/mb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/utils/mb
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	conv.o \
	mbutils.o \
	stringinfo_mb.o \
	wstrcmp.o \
	wstrncmp.o

include $(top_srcdir)/src/adbmgrd/common.mk
