#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/brin
#
# IDENTIFICATION
#    src/adbmgrd/access/brin/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/brin
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	brin.o \
	brin_bloom.o \
	brin_inclusion.o \
	brin_minmax.o \
	brin_minmax_multi.o \
	brin_pageops.o \
	brin_revmap.o \
	brin_tuple.o \
	brin_validate.o \
	brin_xlog.o

include $(top_srcdir)/src/adbmgrd/common.mk
