#----------------------------------------------------------------------------
#
# Postgres-XC backend method makefile
#
# Copyright(c) 2010-2012 Postgres-XC Development Group
#
# src/backend/pgxc/Makefile
#
#-----------------------------------------------------------------------------
subdir = src/backend/pgxc
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = xc_maintenance_mode locator nodemgr pool copy cluster

include $(top_srcdir)/src/backend/common.mk
