#-------------------------------------------------------------------------
#
# Makefile --
#    Makefile for cluster functionality
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/cluster
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = pause.o cluster_barrier.o

include $(top_srcdir)/src/backend/common.mk
