#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/table
#
# IDENTIFICATION
#    src/adbmgrd/access/table/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/table
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = table.o tableam.o tableamapi.o

include $(top_srcdir)/src/adbmgrd/common.mk
