#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for statistics
#
# IDENTIFICATION
#    src/adbmgrd/statistics/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/statistics
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = extended_stats.o dependencies.o mcv.o mvdistinct.o

include $(top_srcdir)/src/adbmgrd/common.mk
