#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/index
#
# IDENTIFICATION
#    src/agtm/access/index/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/access/index
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = amapi.o amvalidate.o genam.o indexam.o

include $(top_srcdir)/src/agtm/common.mk
