#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/common
#
# IDENTIFICATION
#    src/adbmgrd/access/common/Makefile
#
#-------------------------------------------------------------------------

subdir = src/adbmgrd/access/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	attmap.o \
	bufmask.o \
	detoast.o \
	heaptuple.o \
	indextuple.o \
	printsimple.o \
	printtup.o \
	relation.o \
	reloptions.o \
	scankey.o \
	session.o \
	syncscan.o \
	toast_compression.o \
	toast_internals.o \
	tupconvert.o \
	tupdesc.o

include $(top_srcdir)/src/adbmgrd/common.mk
