set grammar to oracle;
set datestyle='ISO,YMD';
set timezone to 'PRC';
--IN、NOT IN
create table adv_query_1(id int,name varchar(10),sal number(7,2));
insert into adv_query_1(id,name,sal) values(1, 'mike',5000);
insert into adv_query_1(id,name,sal) values(2, 'Tom',6000.98);
insert into adv_query_1(id,name,sal) values(4, 'Tom','6000.98');
insert into adv_query_1(id,name,sal) values(3, 'Jhon',null);
select * from adv_query_1 order by id;
select name from adv_query_1 where sal IN(5000,6000.98) order by name;
select name from adv_query_1 where sal IN(6000.98,6000.98) order by name;
select name from adv_query_1 where sal IN('6000.98','6000.98') order by name;
select name from adv_query_1 where sal IN(5000) order by name;
select name from adv_query_1 where sal IN('') order by name;
select name from adv_query_1 where sal IN(to_char(5000),to_char(6000.98)) order by name;
select name from adv_query_1 where id IN(to_char(1),to_char(2),to_char(3)) order by name;
select name from adv_query_1 where id IN(to_char(1.00),to_char(2.0),to_char(03)) order by name;
drop table adv_query_1;
--in后面跟子查询
create table adv_query_1(id smallint,name varchar(10));
insert into adv_query_1(id,name) values(1, '1');
insert into adv_query_1(id,name) values(2, '2');
create table adv_query_2(id int,job varchar(20));
insert into adv_query_2(id,job) values(1,'doctor assistant');
insert into adv_query_2(id,job) values(2,'nurse');
select id,name from adv_query_1 where id IN(select id from adv_query_2) order by id;
select id,name from adv_query_1 where id IN(select name from adv_query_1) order by id;
select id,name from adv_query_1 where name IN(select id from adv_query_2) order by id;
select id,job from adv_query_2 where id IN(select name from adv_query_1) order by id;
select id,job from adv_query_2 where id NOT IN(select name from adv_query_1 where id=3) order by id;
select id,job from adv_query_2 where id IN(select name from adv_query_1 where id=1) order by id;
drop table adv_query_1;
drop table adv_query_2;
--between and	
create table adv_query_1(id number,name varchar(10));
insert into adv_query_1(id,name) values(221292, 'Sherry');
insert into adv_query_1(id,name) values(6789, 'Steven');
select * from adv_query_1 where id between 6789 and 221292 order by id;
select * from adv_query_1 where id between '6789' and '221292' order by id;
select * from adv_query_1 where id between 221293 and 6788 order by id;
select * from adv_query_1 where id between to_char(2) and to_char(5) order by id;
drop table adv_query_1;
--日期	
create table adv_query_1(id smallint,indt date,outdt date);
insert into adv_query_1 values(1, to_date('20151230','yyyymmdd'),to_date('20171230','yyyymmdd'));
insert into adv_query_1 values(2, to_date('20161125','yyyymmdd'),to_date('20161225','yyyymmdd'));
insert into adv_query_1 values(3, to_date('20160101','yyyymmdd'),to_date('20160801','yyyymmdd'));
select * from adv_query_1 where to_char(indt,'yyyymmdd') between '20151230' and '20160101' order by id;
select * from adv_query_1 where months_between(outdt,indt) between 12 and 24 order by id;
select id, to_char(numtodsinterval(to_number(outdt-indt),'day'), 'dd') itv from adv_query_1 where numtodsinterval(to_number(outdt-indt),'day') between numtodsinterval(1,'day') and numtodsinterval(25000,'hour') order by id;
drop table adv_query_1;
--LIKE	number
create table adv_query_1(id number(6,2),name char(20), dt date);
insert into adv_query_1 values(980,'apple#America',to_date('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into adv_query_1 values(980.1,'apple#UK',to_date('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from adv_query_1  order by id;;
select * from adv_query_1 where id like '%.%' order by id;;
select * from adv_query_1 where id like '980' order by id;;
select * from adv_query_1 where id like 980 order by id;
select * from adv_query_1 where id like 980.00 order by id;
select * from adv_query_1 where id like '980.00' order by id;
drop table adv_query_1;
--float	
create table adv_query_1(id binary_float,name char(20), dt date);
insert into adv_query_1 values(980,'apple#America',to_date('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into adv_query_1 values(980.1,'apple#UK',to_date('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from adv_query_1 order by id;
select * from adv_query_1 where id like '%.%' order by id;
select * from adv_query_1 where id like '980' order by id;
select * from adv_query_1 where id like 980 order by id;
drop table adv_query_1;
--date、char
create table adv_query_1(id number(6,2),name char(13), dt timestamp);
insert into adv_query_1 values(1,'apple#America',to_timestamp('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into adv_query_1 values(2,'apple#UK',to_timestamp('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into adv_query_1 values(3,'apple',to_timestamp('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from adv_query_1 order by id;
select * from adv_query_1 where name like '%#%' order by id;
select * from adv_query_1 where name like '%ca' order by id;
select * from adv_query_1 where name like 'apple%' order by id;
select * from adv_query_1 where name like '% ' order by id;
select * from adv_query_1 where name like 'apple' order by id;
select * from adv_query_1 where name like 'apple        ' order by id;
select * from adv_query_1 where name like to_char('apple% ') order by id;
select * from adv_query_1 where dt like '%10:30:59%' order by id;
select * from adv_query_1 where dt like '%' order by id;
select * from adv_query_1 where dt like '%%%%%%%%' order by id;
drop table adv_query_1;
--varchar、date	
create table adv_query_1(id int,name varchar(20), dt date);
insert into adv_query_1 values(1,'apple#America',to_date('2015-10-01','yyyy-mm-dd hh24:mi:ss'));
insert into adv_query_1 values(2,'apple#UK',to_date('2015-11-01','yyyy-mm-dd'));
insert into adv_query_1 values(3,'apple',to_date('2015-11-01','yyyy-mm-dd'));
select * from adv_query_1 order by id;
select * from adv_query_1 where name like '%ca' order by id;
select * from adv_query_1 where name like 'apple%' order by id;
select * from adv_query_1 where name like '% ' order by id;
select * from adv_query_1 where name like 'apple' order by id;
select * from adv_query_1 where name like to_char('apple%') order by id;
select * from adv_query_1 where dt like '2015-10-01' order by id;
select * from adv_query_1 where dt like to_date('2015-10-01','YYYY-MM-DD') order by id;
drop table adv_query_1;
--IS NULL	
create table adv_query_1(id int,name varchar(20));
insert into adv_query_1 values(1,'Jack');
insert into adv_query_1 values(2,'');
insert into adv_query_1 values(3,null);
insert into adv_query_1 values(null,null);
select * from adv_query_1 where name is null order by id;
select * from adv_query_1 where name is not null;
select * from adv_query_1 where id is not null and name is null order by id;
select * from adv_query_1 where  name=null;
drop table adv_query_1;
--测试在pg语法下创建表，在oracle下查询
set grammar to default;
create table adv_query_1(id int,name varchar(20));
insert into adv_query_1 values(1,'Jack');
insert into adv_query_1 values(2,'');
insert into adv_query_1 values(3,null);
insert into adv_query_1 values(null,null);
set grammar to oracle;
select * from adv_query_1 where name is null order by id;
select * from adv_query_1 where name is not null;
select * from adv_query_1 where id is not null and name is null order by id;
select * from adv_query_1 where  name=null;
drop table adv_query_1;
--AND 、OR、NOT	优先级	
create table adv_query_1(id int,name varchar(20));
insert into adv_query_1 values(1,'Jack');
insert into adv_query_1 values(2,'Tom');
insert into adv_query_1 values(3,'Tom');
select name from adv_query_1 where id=1 and name='Jack';
select name from adv_query_1 where id=1 and name='Jack' or 1=1 order by id;
select name from adv_query_1 where id=1 and (name='Jack' or 1=1);
select name from adv_query_1 where id=1 or id=2 or id=3 order by id;
select * from adv_query_1 where id=1 or name='Tom' and id=2 order by id;
select * from adv_query_1 where (id=1 or name='Tom') and id=2 order by id;
select * from adv_query_1 where id=1 or name='Tom' and not id=2 order by id;
select * from adv_query_1 where id=1 or not (name='Jack' and id=2) order by id;
select * from adv_query_1 where id=1 or not name='Jack' and id=2 order by id;
drop table adv_query_1;
--distinct
create table adv_query_1(id int,name varchar(20));
insert into adv_query_1 values(1,'Jack');
insert into adv_query_1 values(1,'Rose');
insert into adv_query_1 values(2,'Tom');
insert into adv_query_1 values(3,'Tom');
insert into adv_query_1 values(1,'Jack');
insert into adv_query_1 values(4,'');
insert into adv_query_1 values(null,4);
insert into adv_query_1 values(5,null);
select * from adv_query_1 order by id, name;
select distinct id from adv_query_1 order by id;
select distinct id,name from adv_query_1 order by id, name;
select count(distinct id) from adv_query_1;
select distinct name from adv_query_1 order by name;
select count(distinct name) from adv_query_1;
drop table adv_query_1;
--精度测试	
create table adv_query_1(id number,name varchar(20),addr char(5));
insert into adv_query_1 values(1.00,'Jack','1');
insert into adv_query_1 values(1,to_char('Jack '),'1    ');
insert into adv_query_1 values(1.00,' Jack','    1');
select * from adv_query_1;
select distinct id from adv_query_1 order by id;
select distinct name from adv_query_1 order by name;
select distinct addr from adv_query_1 order by addr;
select count(distinct id) from adv_query_1;
drop table adv_query_1;
--order by	单列、多列	
create table adv_query_1(id int,name varchar(20));
insert into adv_query_1 values(1,'1Jack');
insert into adv_query_1 values(2,'1Rose');
insert into adv_query_1 values(2,'Rose');
insert into adv_query_1 values(3,'Tom');
insert into adv_query_1 values(11,'Jack');
insert into adv_query_1 values(4,'');
select * from adv_query_1 order by id;
select * from adv_query_1 order by name desc;
select * from adv_query_1 order by id,name desc;
drop table adv_query_1;
--group by	一般用法	
create table adv_query_1(id number,name varchar(20),sal number);
insert into adv_query_1 values(1,'rose',1800);
insert into adv_query_1 values(2,'rose',2000.5);
insert into adv_query_1 values(3.00,'Jack',2000);
insert into adv_query_1 values(3,'Tom',2000);
insert into adv_query_1 values(4,'Tom',2000);
insert into adv_query_1 values(5,'Steven',2000.00);
select * from adv_query_1 order by id;
select sal from adv_query_1 group by sal order by sal;
select id,count(id) from adv_query_1 group by id order by id;
select id,count(*) from adv_query_1 group by id,name order by id;
select name,count(*) from adv_query_1 group by name having count(*)>1 order by name;
select name,count(*) from adv_query_1 group by name having name !='Tom' order by name;
select name,count(*) from adv_query_1 group by name order by name;
select name,count(*) from adv_query_1 group by name order by count(*);
drop table adv_query_1;

--view下复杂查询，查出最大一行的所有字段：
create table adv_query_1(id int,name varchar(10),sal number(7,2));
insert into adv_query_1(id,name,sal) values(1, 'mike','5000');
insert into adv_query_1(id,name,sal) values(2, 'Tom','6000.98');
insert into adv_query_1(id,name,sal) values(3, 'Jhon',null);
create view vv as select max(sal) as max_sal from adv_query_1;
select * from vv;
select id,name,sal from adv_query_1,vv where adv_query_1.sal=vv.max_sal;
select id,name,sal from adv_query_1,(select max(sal) as max_sal from adv_query_1) v where adv_query_1.sal=v.max_sal;
drop view vv;
drop table adv_query_1;
