set grammar to oracle;
set datestyle='ISO,YMD';
set timezone to 'PRC';
--IN、NOT IN
create table tt(id int,name varchar(10),sal number(7,2));
insert into tt(id,name,sal) values(1, 'mike',5000);
insert into tt(id,name,sal) values(2, 'Tom',6000.98);
insert into tt(id,name,sal) values(4, 'Tom','6000.98');
insert into tt(id,name,sal) values(3, 'Jhon',null);
select * from tt order by id;
select name from tt where sal IN(5000,6000.98) order by name;
select name from tt where sal IN(6000.98,6000.98) order by name;
select name from tt where sal IN('6000.98','6000.98') order by name;
select name from tt where sal IN(5000) order by name;
select name from tt where sal IN('') order by name;
select name from tt where sal IN(to_char(5000),to_char(6000.98)) order by name;
select name from tt where id IN(to_char(1),to_char(2),to_char(3)) order by name;
select name from tt where id IN(to_char(1.00),to_char(2.0),to_char(03)) order by name;
drop table tt;
--in后面跟子查询
create table tt(id smallint,name varchar(10));
insert into tt(id,name) values(1, '1');
insert into tt(id,name) values(2, '2');
create table aa(id int,job varchar(20));
insert into aa(id,job) values(1,'doctor assistant');
insert into aa(id,job) values(2,'nurse');
select id,name from tt where id IN(select id from aa) order by id;
select id,name from tt where id IN(select name from tt) order by id;
select id,name from tt where name IN(select id from aa) order by id;
select id,job from aa where id IN(select name from tt) order by id;
select id,job from aa where id NOT IN(select name from tt where id=3) order by id;
select id,job from aa where id IN(select name from tt where id=1) order by id;
drop table tt;
drop table aa;
--between and	
create table tt(id number,name varchar(10));
insert into tt(id,name) values(221292, 'Sherry');
insert into tt(id,name) values(6789, 'Steven');
select * from tt where id between 6789 and 221292 order by id;
select * from tt where id between '6789' and '221292' order by id;
select * from tt where id between 221293 and 6788 order by id;
select * from tt where id between to_char(2) and to_char(5) order by id;
drop table tt;
--日期	
create table tt(id smallint,indt date,outdt date);
insert into tt values(1, to_date('20151230','yyyymmdd'),to_date('20171230','yyyymmdd'));
insert into tt values(2, to_date('20161125','yyyymmdd'),to_date('20161225','yyyymmdd'));
insert into tt values(3, to_date('20160101','yyyymmdd'),to_date('20160801','yyyymmdd'));
select * from tt where to_char(indt,'yyyymmdd') between '20151230' and '20160101' order by id;
select * from tt where months_between(outdt,indt) between 12 and 24 order by id;
select id, to_char(numtodsinterval(to_number(outdt-indt),'day'), 'dd') itv from tt where numtodsinterval(to_number(outdt-indt),'day') between numtodsinterval(1,'day') and numtodsinterval(25000,'hour') order by id;
drop table tt;
--LIKE	number
create table tt(id number(6,2),name char(20), dt date);
insert into tt values(980,'apple#America',to_date('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(980.1,'apple#UK',to_date('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from tt  order by id;;
select * from tt where id like '%.%' order by id;;
select * from tt where id like '980' order by id;;
select * from tt where id like 980 order by id;
select * from tt where id like 980.00 order by id;
select * from tt where id like '980.00' order by id;
drop table tt;
--float	
create table tt(id binary_float,name char(20), dt date);
insert into tt values(980,'apple#America',to_date('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(980.1,'apple#UK',to_date('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from tt order by id;
select * from tt where id like '%.%' order by id;
select * from tt where id like '980' order by id;
select * from tt where id like 980 order by id;
drop table tt;
--date、char
create table tt(id number(6,2),name char(13), dt timestamp);
insert into tt values(1,'apple#America',to_timestamp('2015-10-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(2,'apple#UK',to_timestamp('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(3,'apple',to_timestamp('2015-11-01 10:30:59','yyyy-mm-dd hh24:mi:ss'));
select * from tt order by id;
select * from tt where name like '%#%' order by id;
select * from tt where name like '%ca' order by id;
select * from tt where name like 'apple%' order by id;
select * from tt where name like '% ' order by id;
select * from tt where name like 'apple' order by id;
select * from tt where name like 'apple        ' order by id;
select * from tt where name like to_char('apple% ') order by id;
select * from tt where dt like '%10:30:59%' order by id;
select * from tt where dt like '%' order by id;
select * from tt where dt like '%%%%%%%%' order by id;
drop table tt;
--varchar、date	
create table tt(id int,name varchar(20), dt date);
insert into tt values(1,'apple#America',to_date('2015-10-01','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(2,'apple#UK',to_date('2015-11-01','yyyy-mm-dd'));
insert into tt values(3,'apple',to_date('2015-11-01','yyyy-mm-dd'));
select * from tt order by id;
select * from tt where name like '%ca' order by id;
select * from tt where name like 'apple%' order by id;
select * from tt where name like '% ' order by id;
select * from tt where name like 'apple' order by id;
select * from tt where name like to_char('apple%') order by id;
select * from tt where dt like '2015-10-01' order by id;
select * from tt where dt like to_date('2015-10-01','YYYY-MM-DD') order by id;
drop table tt;
--IS NULL	
create table tt(id int,name varchar(20));
insert into tt values(1,'Jack');
insert into tt values(2,'');
insert into tt values(3,null);
insert into tt values(null,null);
select * from tt where name is null order by id;
select * from tt where name is not null;
select * from tt where id is not null and name is null order by id;
select * from tt where  name=null;
drop table tt;
--测试在pg语法下创建表，在oracle下查询
set grammar to default;
create table tt(id int,name varchar(20));
insert into tt values(1,'Jack');
insert into tt values(2,'');
insert into tt values(3,null);
insert into tt values(null,null);
set grammar to oracle;
select * from tt where name is null order by id;
select * from tt where name is not null;
select * from tt where id is not null and name is null order by id;
select * from tt where  name=null;
drop table tt;
--AND 、OR、NOT	优先级	
create table tt(id int,name varchar(20));
insert into tt values(1,'Jack');
insert into tt values(2,'Tom');
insert into tt values(3,'Tom');
select name from tt where id=1 and name='Jack';
select name from tt where id=1 and name='Jack' or 1=1 order by id;
select name from tt where id=1 and (name='Jack' or 1=1);
select name from tt where id=1 or id=2 or id=3 order by id;
select * from tt where id=1 or name='Tom' and id=2 order by id;
select * from tt where (id=1 or name='Tom') and id=2 order by id;
select * from tt where id=1 or name='Tom' and not id=2 order by id;
select * from tt where id=1 or not (name='Jack' and id=2) order by id;
select * from tt where id=1 or not name='Jack' and id=2 order by id;
drop table tt;
--distinct
create table tt(id int,name varchar(20));
insert into tt values(1,'Jack');
insert into tt values(1,'Rose');
insert into tt values(2,'Tom');
insert into tt values(3,'Tom');
insert into tt values(1,'Jack');
insert into tt values(4,'');
insert into tt values(null,4);
insert into tt values(5,null);
select * from tt order by id, name;
select distinct id from tt order by id;
select distinct id,name from tt order by id, name;
select count(distinct id) from tt;
select distinct name from tt order by name;
select count(distinct name) from tt;
drop table tt;
--精度测试	
create table tt(id number,name varchar(20),addr char(5));
insert into tt values(1.00,'Jack','1');
insert into tt values(1,to_char('Jack '),'1    ');
insert into tt values(1.00,' Jack','    1');
select * from tt;
select distinct id from tt order by id;
select distinct name from tt order by name;
select distinct addr from tt order by addr;
select count(distinct id) from tt;
drop table tt;
--order by	单列、多列	
create table tt(id int,name varchar(20));
insert into tt values(1,'1Jack');
insert into tt values(2,'1Rose');
insert into tt values(2,'Rose');
insert into tt values(3,'Tom');
insert into tt values(11,'Jack');
insert into tt values(4,'');
select * from tt order by id;
select * from tt order by name desc;
select * from tt order by id,name desc;
drop table tt;
--group by	一般用法	
create table tt(id number,name varchar(20),sal number);
insert into tt values(1,'rose',1800);
insert into tt values(2,'rose',2000.5);
insert into tt values(3.00,'Jack',2000);
insert into tt values(3,'Tom',2000);
insert into tt values(4,'Tom',2000);
insert into tt values(5,'Steven',2000.00);
select * from tt order by id;
select sal from tt group by sal order by sal;
select id,count(id) from tt group by id order by id;
select id,count(*) from tt group by id,name order by id;
select name,count(*) from tt group by name having count(*)>1 order by name;
select name,count(*) from tt group by name having name !='Tom' order by name;
select name,count(*) from tt group by name order by name;
select name,count(*) from tt group by name order by count(*);
drop table tt;

--view下复杂查询，查出最大一行的所有字段：
create table tt(id int,name varchar(10),sal number(7,2));
insert into tt(id,name,sal) values(1, 'mike','5000');
insert into tt(id,name,sal) values(2, 'Tom','6000.98');
insert into tt(id,name,sal) values(3, 'Jhon',null);
create view vv as select max(sal) as max_sal from tt;
select * from vv;
select id,name,sal from tt,vv where tt.sal=vv.max_sal;
select id,name,sal from tt,(select max(sal) as max_sal from tt) v where tt.sal=v.max_sal;
drop view vv;
drop table tt;
