set grammar to oracle;
set datestyle='ISO,YMD';
set timezone = 8;
--基本查询
create table base_query_1(id int,name varchar(10),sal binary_float, regdt timestamp default(to_date(' 2016-01-01 00:00:00','YYYY-MM-DD hh24:mi:ss')));
insert into base_query_1(id,name,sal) values(1, 'mike',3008.90);
select * from base_query_1;
select name, regdt from base_query_1;
select base_query_1.name from base_query_1;
select regdt,name,sal from base_query_1;
drop table base_query_1;
--WHERE	基本运算符号
create table base_query_1(id int,name varchar(10),sal binary_float, regdt timestamp default(to_date(' 2016-01-01 00:00:00','YYYY-MM-DD hh24:mi:ss')));
insert into base_query_1(id,name,sal) values(1, 'mike',3008.90);
insert into base_query_1 values(2, 'Tom',4380,to_timestamp('2016-3-24 15:09:50','YYYY-MM-DD hh24:mi:ss'));
select * from base_query_1 where id=2;
select * from base_query_1 where id>=1;
select * from base_query_1 where id<2;
select * from base_query_1 where id*2-1=1;
select name from base_query_1 where regdt=to_timestamp('2016-3-24 15:09:50','YYYY-MM-DD hh24:mi:ss');
drop table base_query_1;
--||连接不同列
create table base_query_1(id int,name varchar(10));
insert into base_query_1 values(1,'Mike');
insert into base_query_1 values(2,'Jack');
select id||name as id_name from base_query_1;
select to_char(id)||name as id_name from base_query_1;
drop table base_query_1;
create table base_query_1(id number,sal number);
insert into base_query_1 values(1,100);
insert into base_query_1 values(2,200);
select id||sal as id_sal from base_query_1 order by id;
drop table base_query_1;
--不同数据类型
--timestamp	
create table base_query_1(id int, dt timestamp default(to_date(' 2016-01-01 00:00:00','YYYY-MM-DD hh24:mi:ss')));
insert into base_query_1(id) values(1);
insert into base_query_1 values(2,to_timestamp('2016-03-15 15:09:50','YYYY-MM-DD hh24:mi:ss'));
insert into base_query_1 values(3,to_date('2016-03-15 15:09:50','YYYY-MM-DD hh24:mi:ss'));
select * from base_query_1 order by id;
select * from base_query_1 where dt=to_date('2016-03-15 15:09:50','YYYY-MM-DD hh24:mi:ss') order by id;
select * from base_query_1 where dt=to_timestamp('2016-03-15 15:09:50','YYYY-MM-DD hh24:mi:ss') order by id;
select * from base_query_1 where dt=to_timestamp('2016-03-16 15:09:50','YYYY-MM-DD hh24:mi:ss')- NUMTODSINTERVAL(1, 'day') order by id;
select * from base_query_1 where dt<to_timestamp('2016-03-16','YYYY-MM-DD') order by id;
select * from base_query_1 where dt between to_date('2016-03-15','YYYY-MM-DD') and to_date('2016-03-16','YYYY-MM-DD') order by id;
select * from base_query_1 where dt between to_date('2016-03-15 03:09:00 pm','YYYY-MM-DD hh:mi:ss pm') and to_date('2016-03-16','YYYY-MM-DD') order by id;
drop table base_query_1;
--timestamp with time zone
create table base_query_1(id int, dt timestamp with time zone);
insert into base_query_1 values(1,timestamp'2016-03-15 15:09:50' at time zone '0:00');
insert into base_query_1 values(3,to_timestamp_tz('2016-03-15 15:09:50 +8:00','YYYY-MM-DD hh24:mi:ss tzh:tzm'));
select * from base_query_1;
select * from base_query_1 where dt<timestamp'2016-03-15 15:09:50' at time zone '4:00';
drop table base_query_1;
--interval
create table base_query_1(id int, itv interval year(1) to month);
insert into base_query_1 values(1,numtoyminterval(3,'year')+numtoyminterval(3,'month'));
insert into base_query_1 values(2,numtoyminterval(8,'month'));
insert into base_query_1 values(2,numtodsinterval(20,'day'));
select * from base_query_1 order by id;
select * from base_query_1 where itv < numtoyminterval(3,'year');
select * from base_query_1 where itv = numtoyminterval(10,'month');
select * from base_query_1 where itv between numtoyminterval(10,'month') and numtodsinterval(1500,'day');
drop table base_query_1;
--float：不同精度和类型
create table base_query_1(id int,name varchar(10),sal binary_float, regdt timestamp default(to_date(' 2016-01-01 00:00:00','YYYY-MM-DD hh24:mi:ss')));
insert into base_query_1(id,name,sal) values(1, 'mike',3008.90);
select name,sal from base_query_1;
select name,sal from base_query_1 where sal=3008.90;
select name,sal from base_query_1 where sal=3008.9;
select name,sal from base_query_1 where sal=3008.9000;
select name,sal from base_query_1 where sal = 3.009E+003;
select name,sal from base_query_1 where sal = to_number(3008.90);
select name,sal from base_query_1 where sal = '3008.90';
select name,sal from base_query_1 where sal = '3008.9';
select name,sal from base_query_1 where sal = '3008.9000';
select name,sal from base_query_1 where sal = to_char(3008.90);
select name,sal from base_query_1 where sal = abs(-3008.90);
drop table base_query_1;
--int型
create table base_query_1(id int,name varchar(10),sal integer);
insert into base_query_1(id,name,sal) values(1, 'mike',3008.90);
insert into base_query_1(id,name,sal) values(2, 'mike',2500);
select name,sal from base_query_1 order by sal;
select name,sal from base_query_1 where id=1.0;
select name,sal from base_query_1 where sal=3009;
select name,sal from base_query_1 where sal=3009.0;
select name,sal from base_query_1 where id='1';
select name,sal from base_query_1 where id=to_number(1);
select name,sal from base_query_1 where id=to_char(1);
select name,sal from base_query_1 where id=to_char(1.0);
select name,sal from base_query_1 where sal='3009';
select name,sal from base_query_1 where sal=to_number(3009);
select name,sal from base_query_1 where sal=to_char(25000);
select name,sal from base_query_1 where sal=abs(-25000);
select name,sal from base_query_1 where sal='';
drop table base_query_1;
--varchar	
create table base_query_1(id int,name varchar(10),info varchar(50));
insert into base_query_1(id,name,info) values(1, 'mike','5000');
insert into base_query_1(id,name,info) values(2, '2',to_date('2015-02-12','YYYY-MM-DD'));
insert into base_query_1(id,name,info) values(3, null,'');
select * from base_query_1 order by id;
select name from base_query_1 where name='mike';
select name from base_query_1 where name=2;
select name from base_query_1 where info=to_date('2015-02-12','YYYY-MM-DD');
select name from base_query_1 where info='';
select name from base_query_1 where info=null;
select name from base_query_1 where info is null;
drop table base_query_1;
--number	
create table base_query_1(id number(3,1));
insert into base_query_1(id) values(1);
insert into base_query_1(id) values(2.17);
select * from base_query_1 order by id;
select * from base_query_1 where id=1.00000000;
select * from base_query_1 where id=000001;
select * from base_query_1 where id=tanh(100);
select * from base_query_1 where id=exp(0);
select * from base_query_1 where id='2.2';
select * from base_query_1 where id=to_char(2.2);
select * from base_query_1 where id=to_char(2.20);
select * from base_query_1 where id=to_number(2.200,'9.000');
select * from base_query_1 where id= 2.2::binary_float;
select * from base_query_1 where id= 2.2::binary_double;
drop table base_query_1;
--为子查询取别名
create table base_query_1(id int,sal binary_float);
insert into base_query_1 values(1,1880.23);
insert into base_query_1 values(2,17000);
create table base_query_2(id int,sal binary_float);
insert into base_query_2 values(1,5000);
insert into base_query_2 values(2,1000);
select t.sal money from base_query_1 t,base_query_2 a where t.sal>a.sal;
select base_query_1.sal money from base_query_1,base_query_2 a where base_query_1.sal>a.sal;
select base_query_1.id from base_query_1, (select id,sal from base_query_2 where id<2) a where base_query_1.id=a.id;
select id from (select id,sal from base_query_2 where id<3) a where a.id>1;
select id from (select id,sal money from base_query_2 where id<3) a where a.money<5000;
drop table base_query_1;
drop table base_query_2;