set grammar to oracle;

SELECT NLS_CHARSET_ID('gbk') FROM DUAL; 
SELECT NLS_CHARSET_ID('utf8') FROM DUAL; 
SELECT NLS_CHARSET_ID('unicode') FROM DUAL; 
SELECT NLS_CHARSET_ID('aaa') FROM DUAL; 
SELECT NLS_CHARSET_ID(123) FROM DUAL; 