set grammar to oracle;

SELECT NLS_CHARSET_NAME(2) FROM DUAL;
SELECT NLS_CHARSET_NAME(6) FROM DUAL;
SELECT NLS_CHARSET_NAME(37) FROM DUAL;
SELECT NLS_CHARSET_NAME(888) FROM DUAL;
SELECT NLS_CHARSET_NAME('qw') FROM DUAL;