set grammar to oracle;
select remainder(7,5) from dual;
select remainder(11.9,3) from dual;
select remainder(-99.8768678,4) from dual;
select remainder(-5.6,-2.5) from dual;
select remainder(0,2) from dual;
select remainder(0,0) from dual;
select remainder(3,0) from dual;
select remainder(exp(4),3) from dual;
select remainder(sin(0.9),tan(1)) from dual;
select remainder(1.98*4/(1.9+1.1),1.5*2) from dual;
select remainder(to_number('34'),3) from dual;
select remainder(to_char(29),3) from dual;
select remainder('7',5) from dual;
select remainder(11.9,'3') from dual;
select remainder('-8.1','4') from dual;
select remainder('008','4.000') from dual;
select remainder('0',2) from dual;
select remainder('NaN',2) from dual;
select remainder('NaN','NaN') from dual;
select remainder(5,'NaN') from dual;
select remainder('',null) from dual;
select remainder(null,3) from dual;
select remainder('','') from dual;

CREATE TABLE t4test (id int,num int);
insert into t4test values(1,remainder(1211,12));
insert into t4test values(2,remainder(12234,23));
select * from t4test order by id;
update t4test set num=remainder(num,4.5);
select * from t4test order by id;
drop table t4test;