set grammar to oracle;
select cosh(exp(2)) from dual;
select cosh(-1) from dual;
select cosh('0.9') from dual;
select cosh(0) from dual;
select cosh(to_char(0.5)) from dual;
select cosh('0.9') from dual;
select cosh(null) from dual;
select cosh('') from dual;