set grammar to oracle;
set datestyle='ISO,YMD';
select instr('abc','bc') from dual;
select instr(to_char('abc'),to_char('bc')) from dual;
select instr('爱存不存','存',1,2) from dual;
select instr(1234,23) from dual;
select instr(to_number(123.56),'.') from dual;
select instr(exp(2),0)  from dual;
select instr(exp(2),exp(2))  from dual;
select instr(to_date('2015-06-06 20:50:30','yyyy-mm-dd hh24:mi:ss'),'15') from dual;
select instr('!@#$%^&*()~','^')  from dual;
select instr('abc
sw','
s') from dual;
select instr('abcswcs','cs',1,2) from dual;
select instr('abcswcs','cs',1000000000) from dual;
select instr('abcswcs','cs',-100) from dual;
select instr('abcswcs','cs',-1) from dual;
select instr('abcswcs','cs','',-1) from dual;
select instr('abcswcs','cs',0) from dual;
select instr('abcswcs','cs',1,10000000000) from dual;
select instr('','')  from dual;
select instr(null,'a') from dual;
select instr('abc','') from dual;
create table instrtbl2 (name varchar2(10));
insert into instrtbl2 values('1bd2');
insert into instrtbl2 values('3cd');
insert into instrtbl2 values('mmd');
insert into instrtbl2 values('ccd');
select * from instrtbl2 where instr(name,'d')  >0 order by name;
drop table instrtbl2;
