set grammar to oracle;
create table lnnvltbl(name varchar(10), id int);
insert into lnnvltbl values(null, 1); 
insert into lnnvltbl values('', 2);
insert into lnnvltbl values ('null',3);
insert into lnnvltbl values('s', 4);
insert into lnnvltbl values ('ss',5);
select * from lnnvltbl where lnnvl(name is not null) order by id;
select * from lnnvltbl where lnnvl(name is null) order by id;
select * from lnnvltbl where lnnvl(name like 's%') order by id;
select * from lnnvltbl where lnnvl(name ='s') order by id;
select * from lnnvltbl where lnnvl(name like 's%') and id <4 order by id;
select * from lnnvltbl where lnnvl(id <2 or id >4) order by id;
select * from lnnvltbl where lnnvl(id in(1,3)) order by id;
select * from lnnvltbl where lnnvl(id between 1 and 3) order by id;
drop table lnnvltbl;
