set grammar to oracle;
set datestyle='ISO,YMD';
create table aa(id int, dt timestamp);
insert into aa values(1,to_date('2000-3-31','YYYY-MM-DD'));
insert into aa values(2,to_date('2000-2-29','YYYY-MM-DD'));
select id, next_day(dt,'MONDAY') from aa;
select id, next_day(dt,'MON') from aa;
select id, next_day(dt,'Mond') from aa;
select id, next_day(dt,2) from aa;
select id, next_day(dt,2.4) from aa;
drop table aa;
