set grammar to oracle;
set datestyle='ISO,YMD';
create table nextdaytbl(id int, dt timestamp);
insert into nextdaytbl values(1,to_date('2000-3-31','YYYY-MM-DD'));
insert into nextdaytbl values(2,to_date('2000-2-29','YYYY-MM-DD'));
select id, next_day(dt,'MONDAY') from nextdaytbl;
select id, next_day(dt,'MON') from nextdaytbl;
select id, next_day(dt,'Mond') from nextdaytbl;
select id, next_day(dt,2) from nextdaytbl;
select id, next_day(dt,2.4) from nextdaytbl;
drop table nextdaytbl;
