set grammar to oracle;
select nls_initcap('ab cde') from dual;
select nls_initcap('AAb  CDE') from dual;
select nls_initcap('\?!@#$%^&*()sa') from dual;
select nls_initcap('AA\?!@#$%^&*()AA') from dual;
select nls_initcap('\?!@#ss$%^&*()sC') from dual;
select nls_initcap('test你test好test') from dual;
select nls_initcap('1234SOU') from dual;
select nls_initcap(to_char('suv')) from dual;
select nls_initcap(to_number('NaN')) from dual;
