set grammar to oracle;
create table aa(id int,name varchar(20), cont  varchar(20));
insert into aa values(1,'345','345');
insert into aa values(2,'345abc','345');
insert into aa values(3,'','');
insert into aa values(4,'abc','abcd');
insert into aa values(5,'mike',null);
insert into aa values(6,null,null);
select * from aa where regexp_like(name,'345');
select * from aa where regexp_like(name,to_char(345));
select * from aa where regexp_like(name,345);
select * from aa where regexp_like(name,to_number('345'));
select * from aa where regexp_like(name,exp(1));
select * from aa where regexp_like(name,cont);
select * from aa where regexp_like(name,'345abcd');
select * from aa where regexp_like(name,'');
select * from aa where regexp_like('',name);
select * from aa where regexp_like('','');
select * from aa where regexp_like(name,null);
select * from aa where regexp_like(null,name);
drop table aa;