set grammar to oracle;
create table regliketbl(id int,name varchar(20), cont  varchar(20));
insert into regliketbl values(1,'345','345');
insert into regliketbl values(2,'345abc','345');
insert into regliketbl values(3,'','');
insert into regliketbl values(4,'abc','abcd');
insert into regliketbl values(5,'mike',null);
insert into regliketbl values(6,null,null);
select * from regliketbl where regexp_like(name,'345');
select * from regliketbl where regexp_like(name,to_char(345));
select * from regliketbl where regexp_like(name,345);
select * from regliketbl where regexp_like(name,to_number('345'));
select * from regliketbl where regexp_like(name,exp(1));
select * from regliketbl where regexp_like(name,cont);
select * from regliketbl where regexp_like(name,'345abcd');
select * from regliketbl where regexp_like(name,'');
select * from regliketbl where regexp_like('',name);
select * from regliketbl where regexp_like('','');
select * from regliketbl where regexp_like(name,null);
select * from regliketbl where regexp_like(null,name);
drop table regliketbl;