set grammar to oracle;
--select rpad('~！@#￥%er', 20) from dual;
--select rpad('你好', 5) from dual;
select rpad('cd  ae',5) from dual;
select rpad(to_char(45), 5) from dual;
select rpad(3.545, 5) from dual;
select rpad(4, 5) from dual;
select rpad('a','4') from dual;
select rpad('a','4.84') from dual;
select rpad('abcdegf',3) from dual;
--select rpad('你好',3) from dual;
select rpad('abcdegf',tan(1)) from dual;
--select rpad('abcdegf',100*100) from dual;
select rpad('abc',-2) from dual;
select rpad('abc',5,'*') from dual;
select rpad('abc',5,'123456') from dual;
select rpad('abc',5,' ') from dual;
select rpad('abc',5,6) from dual;
select rpad('abc',5,1.6) from dual;
select rpad('abc',5,to_char(2)) from dual;
select rpad('abc',5,to_number(2)) from dual;
select rpad('abc',5,3*2) from dual;
select rpad('abc',5,tan(2)) from dual;
--select rpad('abc',5,'你好') from dual;
select rpad('',null) from dual;
select rpad(null,null,'') from dual;