set grammar to oracle;
set datestyle ='ISO,YMD';
--count
create table tt(id int,name varchar(20));
insert into tt values(1,'Jack');
insert into tt values(1,'Rose');
insert into tt values('','');
insert into tt values(1,'');
select * from tt order by name;
select count(*) from tt where id=1;
select count(name) from tt where id=1;
select count(*) from tt;
select count(id) from tt;
drop table tt;
--sum
create table tt(name char(5),sal number);
insert into tt values('Jack',5000);
insert into tt values('Rose',5000.0);
insert into tt values('',4500.8);
insert into tt values('','');
insert into tt values('Jack',5000.0);
select * from tt order by name, sal;
select sum(sal) from tt;
select name,sum(sal) from tt where name='Jack' group by name order by name;
select sum(sal) as total from tt where name='Jack';
drop table tt;
--avg
create table tt(name char(5),sal number);
insert into tt values('Jack',5000);
insert into tt values('Rose',5000.07);
insert into tt values('',4500.8);
insert into tt values('','');
insert into tt values('Jack',5000.3);
insert into tt values('Jhon',567.389);
insert into tt values('lucy',0.0006);
insert into tt values('Lili',1.1);
select * from tt order by name, sal;
select avg(sal) from tt;
select sum(*),avg(sal) from tt;
select count(*),sum(sal),avg(sal),(count(*)-1)*avg(sal) as total from tt;
drop table tt;
--max/min
create table tt(id char(5),sal number);
insert into tt values('1',5000);
insert into tt values('2',5000.00);
insert into tt values('6.00','');
insert into tt values('3',4000.3);
insert into tt values('4',567.389);
insert into tt values('5',0.0006);
select * from tt order by id;
select to_number(max(sal)) from tt;
select max(id) from tt;
select min(sal) from tt;
select min(id) from tt;
select sal,max(id) from tt group by sal order by sal;
drop table tt;
--不同数据类型测试
--字符数字
create table tt(id char(5),sal number);
insert into tt values('1',5000);
insert into tt values('1.00',5000.00);
insert into tt values('',4500.8);
insert into tt values('2','');
insert into tt values('3',3000.3);
insert into tt values('4',567.389);
insert into tt values('5',0.0006);
select * from tt order by id;
select max(id) from tt;
select min(id) from tt;
select min(id) from tt;
select avg(id) from tt;
select sum(id) from tt;
drop table tt;
--字符字母	
create table tt(id char(5),sal binary_float);
insert into tt values('Jack',123.9);
insert into tt values('Tom',123.90);
insert into tt values('a',123);
select * from tt order by id;
select max(id) from tt;
select min(id) from tt;
select max(sal) from tt group by sal;
select sal,min(id) from tt group by sal;
select sal,max(id) from tt group by sal;
drop table tt;
--日期	
create table tt(id number,dt date);
insert into tt values(1,to_date('2015-1-1','yyyy-mm-dd'));
insert into tt values(2,to_timestamp('2015-1-2 08:10:09','yyyy-mm-dd hh24:mi:ss'));
insert into tt values(3,to_timestamp('2015-1-2 09:10:09','yyyy-mm-dd hh24:mi:ss'));
select * from tt order by id;
select min(dt) from tt;
select max(dt) from tt;
drop table tt;
