set grammar to oracle;
set datestyle ='ISO,YMD';
--count
create table set_func_tbl1(id int,name varchar(20));
insert into set_func_tbl1 values(1,'Jack');
insert into set_func_tbl1 values(1,'Rose');
insert into set_func_tbl1 values('','');
insert into set_func_tbl1 values(1,'');
select * from set_func_tbl1 order by name;
select count(*) from set_func_tbl1 where id=1;
select count(name) from set_func_tbl1 where id=1;
select count(*) from set_func_tbl1;
select count(id) from set_func_tbl1;
drop table set_func_tbl1;
--sum
create table set_func_tbl1(name char(5),sal number);
insert into set_func_tbl1 values('Jack',5000);
insert into set_func_tbl1 values('Rose',5000.0);
insert into set_func_tbl1 values('',4500.8);
insert into set_func_tbl1 values('','');
insert into set_func_tbl1 values('Jack',5000.0);
select * from set_func_tbl1 order by name, sal;
select sum(sal) from set_func_tbl1;
select name,sum(sal) from set_func_tbl1 where name='Jack' group by name order by name;
select sum(sal) as total from set_func_tbl1 where name='Jack';
drop table set_func_tbl1;
--avg
create table set_func_tbl1(name char(5),sal number);
insert into set_func_tbl1 values('Jack',5000);
insert into set_func_tbl1 values('Rose',5000.07);
insert into set_func_tbl1 values('',4500.8);
insert into set_func_tbl1 values('','');
insert into set_func_tbl1 values('Jack',5000.3);
insert into set_func_tbl1 values('Jhon',567.389);
insert into set_func_tbl1 values('lucy',0.0006);
insert into set_func_tbl1 values('Lili',1.1);
select * from set_func_tbl1 order by name, sal;
select avg(sal) from set_func_tbl1;
select sum(*),avg(sal) from set_func_tbl1;
select count(*),sum(sal),avg(sal),(count(*)-1)*avg(sal) as total from set_func_tbl1;
drop table set_func_tbl1;
--max/min
create table set_func_tbl1(id char(5),sal number);
insert into set_func_tbl1 values('1',5000);
insert into set_func_tbl1 values('2',5000.00);
insert into set_func_tbl1 values('6.00','');
insert into set_func_tbl1 values('3',4000.3);
insert into set_func_tbl1 values('4',567.389);
insert into set_func_tbl1 values('5',0.0006);
select * from set_func_tbl1 order by id;
select to_number(max(sal)) from set_func_tbl1;
select max(id) from set_func_tbl1;
select min(sal) from set_func_tbl1;
select min(id) from set_func_tbl1;
select sal,max(id) from set_func_tbl1 group by sal order by sal;
drop table set_func_tbl1;
--不同数据类型测试
--字符数字
create table set_func_tbl1(id char(5),sal number);
insert into set_func_tbl1 values('1',5000);
insert into set_func_tbl1 values('1.00',5000.00);
insert into set_func_tbl1 values('',4500.8);
insert into set_func_tbl1 values('2','');
insert into set_func_tbl1 values('3',3000.3);
insert into set_func_tbl1 values('4',567.389);
insert into set_func_tbl1 values('5',0.0006);
select * from set_func_tbl1 order by id;
select max(id) from set_func_tbl1;
select min(id) from set_func_tbl1;
select min(id) from set_func_tbl1;
select avg(id) from set_func_tbl1;
select sum(id) from set_func_tbl1;
drop table set_func_tbl1;
--字符字母	
create table set_func_tbl1(id char(5),sal binary_float);
insert into set_func_tbl1 values('Jack',123.9);
insert into set_func_tbl1 values('Tom',123.90);
insert into set_func_tbl1 values('a',123);
select * from set_func_tbl1 order by id;
select max(id) from set_func_tbl1;
select min(id) from set_func_tbl1;
select max(sal) from set_func_tbl1 group by sal;
select sal,min(id) from set_func_tbl1 group by sal;
select sal,max(id) from set_func_tbl1 group by sal;
drop table set_func_tbl1;
--日期	
create table set_func_tbl1(id number,dt date);
insert into set_func_tbl1 values(1,to_date('2015-1-1','yyyy-mm-dd'));
insert into set_func_tbl1 values(2,to_timestamp('2015-1-2 08:10:09','yyyy-mm-dd hh24:mi:ss'));
insert into set_func_tbl1 values(3,to_timestamp('2015-1-2 09:10:09','yyyy-mm-dd hh24:mi:ss'));
select * from set_func_tbl1 order by id;
select min(dt) from set_func_tbl1;
select max(dt) from set_func_tbl1;
drop table set_func_tbl1;
