set grammar to oracle;
--加号	
select 1+1-2 from dual;
select 2+1.78-2.1 from dual;
select 1+'1.0' from dual;
select '1'+'1.0' from dual;
select '1'+'1' from dual;
select 1+to_char(1) from dual;
select to_char(1)+to_char(1.2) from dual;
select 1+to_char(1) from dual;
create table signtbl1(id number,name varchar2(3),ad char(3));
insert into signtbl1 values(1,'1.0','1');
select 1+name from signtbl1;
select 1+ad from signtbl1;
drop table signtbl1;
select 1 + '1.0'::varchar2(3) from dual;
select 1 + '1'::char(3) from dual;
select to_number(1)+'1' from dual;
select 1.0::binary_float+'1' from dual;
select 1.0::float(4)+'1' from dual;	
select to_char(to_date('2014-07-15','YYYY-MM-DD')+numtoyminterval(3,'month'),'yyyy-mm') from dual;
select to_char(numtoyminterval(3,'year') - numtoyminterval(3,'month'),'yyyy-mm') from dual;
--减	
select 1-'1' from dual;
select 1-'1.0' from dual;
select '1'-'1.0' from dual;
select '1'-'1' from dual;
select 1-to_char(1) from dual;
select to_char(1)-to_char(1.2) from dual;
select 1-to_char(1) from dual;
select to_number(1)-'1' from dual;
select 1.0::binary_float-'1' from dual;
select 1.0::float(4)-'1' from dual;
--乘			
select 1*'1' from dual;
select 1*'1.0' from dual;
select '1'*'1.0' from dual;
select '1'*'1' from dual;
select 1*to_char(1) from dual;
select to_char(1)*to_char(1.2) from dual;
select 1*to_char(1) from dual;
select 1 *'1.0'::varchar2(3) from dual;
select 1 * '1'::char(3) from dual;
select to_number(1)*'1' from dual;
select 1.0::binary_float*'1' from dual;
select 1.0::float(4)*'1' from dual;
select to_number(1)*'1' from dual;
--除
select to_number(1)/'1' from dual;
select to_number(5)/to_number(2) from dual;
select to_number(5)/'2' from dual;
select 1.0::binary_float/'1' from dual;
select 1.0::float(4)/'1' from dual;
select 1/'1' from dual;
select 1/'1.0' from dual;
select '1'/'1.0' from dual;
select '1'/'1' from dual;
select 1/to_char(1) from dual;
select to_char(1)/to_char(1.2) from dual;
select 1/to_char(1) from dual;
select 1/'1.0'::varchar2(3) from dual;
select 1/'1'::char(3) from dual;
--比较运算符	
create table signtbl1(id number, name varchar2(3));
insert into signtbl1 values(1,'1.0');
select * from signtbl1 where name = 1;
drop table signtbl1;
select 'equal' from dual where 1>=1.0::varchar(3);
select 'equal' from dual where 1>=to_char(1.0);
select 'equal' from dual where 1>='1.0';
select 'equal' from dual where 1>=1::varchar(3);
select 'equal' from dual where 1>=1::char(3);
create table signtbl1(id number,job varchar(10));
insert into signtbl1 values(1,'IT');
insert into signtbl1 values(2,'doctor');
insert into signtbl1 values(3,'teacher');
insert into signtbl1 values(6,'');
create table signtbl2(id char,avgm number);
insert into signtbl2 values(1.00,10000);
insert into signtbl2 values(2,5000);
insert into signtbl2 values(4,9000);
insert into signtbl2 values(5,null);
select * from signtbl1 where id > all(select id from signtbl2);
drop table signtbl1;
drop table signtbl2;
--between and		
select 1 from dual where 3 between to_char(2) and to_char(5);
select 1 from dual where 3 between 2.0::char(5) and 5.0::varchar(5);
select 1 from dual where 3 between '2.0' and '5.0';
select 1 from dual where to_char(3) between '2.0' and to_char(5);
select 1 from dual where to_char(3) between to_char(2) and to_char(5);
select 1 from dual where 3.0 between '2.0' and '5.0';
select 'equal' from dual where 1=1::number(2);
select 'equal' from dual where 1=1.0::number(3,2);
select 'equal' from dual where 1=1.0::binary_float;
--||	
select 1||2 as result from dual;
select 1.0||2.0 as result from dual;
select to_number(1.20)||to_number(2.0) as result from dual;
select 1.00::binary_double||2.00::binary_double as result from dual;
select 1||to_char('2') as result from dual;
select 1.0||to_char('2') as result from dual;
select to_char(1.0)||to_char(2.0) as result from dual;
select to_char(1.00)||to_char('b') as result from dual;
select 1||'2' as result from dual;
select '1'||'2' as result from dual;
select to_char(1)||to_char(2) as result from dual;
select to_char('1.0')||to_char('2.0') as result from dual;
select to_char('a')||to_char('b') as result from dual;
select to_char(1)||to_char('b') as result from dual;
