set grammar to oracle;
select tanh(exp(2)) from dual;
select tanh(-1) from dual;
select tanh('0.9') from dual;
select tanh(0) from dual;
select tanh(to_char(0.5)) from dual;
select tanh('0.9') from dual;
select tanh(null) from dual;
select tanh('') from dual;
