#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for statistics
#
# IDENTIFICATION
#    src/agtm/statistics/Makefile
#
#-------------------------------------------------------------------------

subdir = src/agtm/statistics
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = extended_stats.o dependencies.o mvdistinct.o

include $(top_srcdir)/src/agtm/common.mk
