#
# Makefile for the access methods module
#
# src/agtm/access/Makefile
#

subdir = src/agtm/access
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = brin common gin gist hash heap index nbtree rmgrdesc spgist \
			  tablesample transam

include $(top_srcdir)/src/agtm/common.mk
